server:
  port: 9003
zuul:
  routes: #路由规则对应到每一个微服务
    shicifang-friend:
      serviceId: shicifang-friend
    shicifang-qa:
      serviceId: shicifang-qa
discoveryServer:
  ribbon:
    eureka:
      enabled: false
servicecomb:
  tracing:
    enabled: true